# Generated by Django 2.1.4 on 2019-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '已发布')], default='draft', max_length=20),
        ),
    ]
